# (PART\*) Versión Español {.unnumbered}

# Introducción {#intro-esp .unnumber}

Actualmente, en [**Datos e Indicadores de América Latina y el Caribe**](https://www.iadb.org/en/sharing-knowledge/data/social-data), se cuenta con indicadores estandarizados y comparables para 26 países de la región (ALC) desde 2006 hasta la actualidad. El acceso a estos indicadores puede realizarse a través de la plataforma o mediante las librerías disponibles en los lenguajes de [***R***](https://github.com/EL-BID/idbsocialdataR), [***Python***](https://github.com/EL-BID/idbsocialdatapy) y [***Stata***](https://github.com/EL-BID/idbsocialdata).

La mayoría de estos indicadores son generados por el Sector Social (SCL) de la Vicepresidencia de Sectores y Conocimiento del BID. La fuente principal para su construcción son las **Encuestas de Hogares y los Censos de Población y Vivienda Armonizados del BID**. Estos indicadores se agrupan en seis áreas de desarrollo social: Demografía y Migración, Vivienda, Pobreza y Desigualdad, Educación, Empleo y Seguridad Social, así como Salud y Protección Social. Lo distintivo de la plataforma radica en la capacidad de visualizar los indicadores sociales en diversos niveles, como género, diversidad, edad, área geográfica de residencia, nivel educativo, quintil de ingreso, entre otros.

Aunque los datos armonizados tienen como fuente principal las encuestas y censos nacionales que generan cada uno de los países, es crucial destacar que estos indicadores no buscan reemplazar ni sustituir a los datos oficiales de ningún país en particular. A pesar de los esfuerzos por garantizar la calidad y comparabilidad de los datos entre países, en algunos casos, los indicadores podrían diferir de las definiciones oficiales de uno o más países. El proceso utilizado para generar cada indicador calculado con las encuestas y censos armonizados se detalla en el [repositorio de Git](https://github.com/EL-BID/armonizacion_microdatos_encuestas_hogares_scl).

Las siguientes secciones describen la metodología de construcción de los indicadores visualizados en el perfil de países, los indicadores desde perspectiva de género y diversidad que tienen como fuente principal los censos de población, y se presentan las fuente de los datos armonizados.
