# (PART\*) English version { .unnumbered}

# Introduction {#intro-eng .unnumber}

Currently in [**Data and Indicators for Latin America and the Caribbean (LAC)**](https://www.iadb.org/en/sharing-knowledge/data/social-data), there are standardized and comparable indicators for 26 countries in the LAC region from 2006 to the present. These indicators can be accessed through the platform or libraries in the [***R***](https://github.com/EL-BID/idbsocialdataR), [***Python***](https://github.com/EL-BID/idbsocialdatapy), and [***Stata languages***](https://github.com/EL-BID/idbsocialdata).

Most of these indicators are generated by the Social Sector (SCL) of the IDB's Vice Presidency for Sectors and Knowledge. The primary sources are the **IDB's harmonized household surveys and population and housing censuses**. These indicators are grouped into six areas of social development: Demography and Migration, Housing, Poverty and Inequality, Education, Employment and Social Security, and Health and Social Protection. The distinctive feature of the platform lies in the ability to visualize social indicators at various levels, such as gender, diversity, age, geographic area of residence, educational level, and income quintile, among others.

Although harmonized data are primarily sourced from national surveys and censuses generated by countries, it is crucial to note that these indicators are not intended to replace or substitute official data from any country. Despite efforts to ensure the quality and comparability of data across countries, in some cases, indicators may differ from the official definitions of one or more countries. The process of generating each indicator calculated with the harmonized surveys and censuses is detailed in the [Git repository](https://github.com/EL-BID/armonizacion_microdatos_encuestas_hogares_scl).

The following sections describe the methodology for constructing the indicators visualized in the country profile, the indicators from a gender and diversity perspective with population censuses as their primary source, and the sources of the harmonized data.
