# Metodología de construcción de indicadores {#indicadores}

A continuación, se describe la metodología utilizada para estimar los indicadores.

## Demografía y migración

### Población {.unnumbered}

-   **Porcentaje de la población por rango de edad**

El porcentaje de población por rango de edad se calcula como el porcentaje de la población en una edad específica con respecto al total de la población. En este contexto, la suma de los porcentajes de todos los grupos de edad representados en la pirámide de población debería ser igual al 100%.

Los rangos de edad definidos para calcular estos indicadores son los siguientes: 0 a 15 años, 16 a 30 años, 31 a 45 años, 46 a 60 años, 61 a 75 años y 76 años o más.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Migrantes {.unnumbered}

-   **Migrantes como porcentaje de la población total**

Se calcula como el porcentaje de migrantes en relación con la población total que reside en el país. Un individuo se considera migrante si informa haber nacido en un país diferente al que se lleva a cabo la encuesta.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Migrantes latinoamericanos**

El porcentaje de migrantes latinoamericanos se calcula tomando en cuenta a la población migrante que proviene de uno de los 26 países de América Latina y el Caribe y que reside en el país donde se realiza la encuesta, en relación con el total de la población migrante.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Migrantes residiendo en el país más de 5 años**

El porcentaje de migrantes antiguos se calcula considerando a la población migrante que ha residido en el país donde se realiza la encuesta durante más de 5 años, en relación con el total de la población migrante.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Diversidad {.unnumbered}

-   **Población indígena**

Porcentaje de la población indígena se calcula como el número de personas que se autoidentifican como indígenas según la clasificación nacional sobre la población total. *Más información sobre cómo se obtiene la información de diversidad ver* [*Recommendation on Diversity Data in the social Sector.*](https://publications.iadb.org/en/recommendations-diversity-data-social-sector)

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Población afrodescendiente**

Porcentaje de la población afrodescendiente se calcula como el número de personas que se autoidentifican como afrodescendiente según la clasificación nacional sobre la población total. *Más información sobre cómo se obtiene la información de diversidad ver* [*Recommendation on Diversity Data in the social Sector.*](https://publications.iadb.org/en/recommendations-diversity-data-social-sector)

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Población con discapacidad**

Porcentaje de personas con discapacidad se calcula como el número de personas que reportan tener al menos alguna dificultad con actividades de la vida diaria según los dominios de las preguntas del ***Washington Group*** sobre el total de la población.

Las preguntas del [*Washington Group*](https://www.washingtongroup-disability.com/fileadmin/uploads/wg/Documents/Questions/Washington_Group_Questionnaire__1_-_WG_Short_Set_on_Functioning__June_2022_.pdf) son uno de los métodos más aceptados para medir la discapacidad en las encuestas nacionales, ya que se centran en las personas que tienen dificultades para realizar actividades diarias, como caminar, ver o recordar. La conceptualización de las preguntas utilizadas para identificar a la población con discapacidad se basa en el modelo de la [*World Health Organization's International Classification of Functioninf, Disability and Health (ICF)*](https://www.who.int/classifications/international-classification-of-functioning-disability-and-health). Cada vez más países de ALC están incluyendo estas preguntas en los cuestionarios de sus encuestas de hogares y censos, pero, por el momento hay información disponible para Bolivia, Chile, Costa Rica, México, Perú.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

## Vivienda {#vivienda}

### Características de los hogares {-}

-   **Porcentaje de hogares con jefatura femenina**

La jefatura femenina de hogar se calcula como el porcentaje de hogares en los cuales una mujer es identificada como la jefa del hogar por el informante de la encuesta, con respecto al total de hogares en el país.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Razón de dependencia**

La razón de dependencia se define como el número de personas menores de 15 años y mayores de 65 años en comparación con la población en edad de trabajar, que se define como la población entre los 15 y 64 años.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Número promedio de miembros del hogar**

Se refiere al promedio del número de personas en un hogar en el país. Se calcula como el número total de personas en el hogar dividido entre el total de hogares en el país.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Acceso a los servicios básicos {-}

-   **Porcentaje de hogares con acceso a los servicios básicos**

Se calcula determinando el porcentaje de hogares que informan tener acceso al servicio básico, dividiendo este número entre el total de hogares. El acceso se calcula de manera individual para cada servicio, teniendo en cuenta las características específicas de cada uno:

**Electricidad:** El acceso se define como los hogares que reportan que la fuente principal de iluminación es la electricidad ya sea pública o privada.

**Agua de acueducto:** El acceso se define como los hogares que reportan que la fuente principal de agua para el consumo es la red de distribución pública.

**Saneamiento:** Según la Organización Mundial de la Salud (OMS) y los Objetivos de Desarrollo Sostenible (ODS), el saneamiento mejorado se define como aquel que previene de manera higiénica el contacto de las personas con excretas humanas. Las instalaciones de saneamiento mejorado más comunes incluyen conexiones cloacales, fosas sépticas, letrinas de pozo mejoradas y ventiladas, así como letrinas con losas. Esta clasificación se realiza de acuerdo con el UNICEF Joint Monitoring Programe (JMP) For Supply and Sanitation (2017).

**Internet:** El hogar reporta tener acceso a conexión local de internet.

**Teléfono celular:** El acceso se define como al menos una persona del hogar cuenta con servicio de teléfono celular.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

## Pobreza y desigualdad

### Población por niveles de ingreso {.unnumbered}

-   **Pobreza extrema (PPA 2011):** Porcentaje de población viviendo en hogares con el ingreso por persona por debajo de la línea de pobreza internacional de \$3.1 dólares por persona al día ajustados a la Paridad de Poder Adquisitivo (PPA) de 2011.

-   **Pobreza moderada (PPA 2011):** Porcentaje de población viviendo en hogares con el ingreso por persona entre \$3.1 y \$5.0 dólares por persona al día ajustados a la Paridad de Poder Adquisitivo (PPA) de 2011.

-   **Vulnerable (PPA 2011):** Porcentaje de población viviendo en hogares con el ingreso por persona entre \$5.0 y \$12.4 dólares por persona al día ajustados a la Paridad de Poder Adquisitivo (PPA) de 2011.

-   **Clase media (PPA 2011):** Porcentaje de población viviendo en hogares con el ingreso por persona entre \$12.4 y \$62.0 dólares por persona al día ajustados a la Paridad de Poder Adquisitivo (PPA) de 2011.

-   **Ingresos altos (PPA 2011):** Porcentaje de población viviendo en hogares con el ingreso por persona mayores a \$62.0 dólares por persona al día ajustados a la Paridad de Poder Adquisitivo (PPA) de 2011.

-   **Población por nivel de ingreso (número de personas):** Se calcula por la multiplicación de la tasa del nivel de ingreso, mencionados anteriormente, por el total de la población.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Desigualdad {.unnumbered}

-   **Coeficiente de Gini:** El coeficiente de Gini del ingreso per cápita del hogar es una medida de desigualdad que compara la distribución real de los ingresos con una distribución perfectamente equitativa. Se basa en la curva de Lorenz, que muestra la acumulación porcentual del total de ingresos en relación con el número acumulado de receptores. En este contexto, el coeficiente de Gini representa la medida del área entre la curva de Lorenz y la línea de igualdad hipotética. Los valores del coeficiente oscilan entre 0 (igualdad completa) y 1 (desigualdad total).

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Ratio de dispersión entre deciles**

El ratio de dispersión entre deciles es una medida de desigualdad que representa el ingreso per cápita de los hogares más ricos como múltiplo del ingreso de los más pobres. Para calcularlos se referencia la distribución del ingreso per cápita de los hogares y se obtiene el percentil 90, 50 y 10 considerando los pesos muestrales.

**Ratio entre el ingreso del decil más rico y el decil más pobre:** Representa cuántas veces más grande es el ingreso per cápita del hogar en el percentil 90 respecto al del percentil 10. Para obtenerlo, se divide el ingreso per cápita del hogar en el percentil 90 entre el ingreso del percentil 10.

**Ratio entre la mediana de ingresos y el decil más pobre:** Representa cuántas veces más grande es el ingreso per cápita del hogar en el percentil 50 respecto al del percentil 10. Para obtenerlo, se divide el ingreso per cápita del hogar en el percentil 50 entre el ingreso del percentil 10.

**Ratio entre el ingreso del decil más rico y la mediana:** Representa cuántas veces más grande es el ingreso per cápita del hogar en el percentil 90 respecto al del percentil 50. Para obtenerlo, se divide el ingreso per cápita del hogar en el percentil 90 entre los del percentil 50.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

## Educación

### Indicadores de asistencia {.unnumbered}

-   **Tasa neta de asistencia**

$$ 
Tasa\ Neta\ de\ Asistencia_i = \frac{Número\ de\ estudiantes\ nivel\ i\ de\ X}{Número\ de\ personas\ de\ X}x 100
$$ donde $i$ es el nivel educativo y $X$ es la edad teórica de cursar ese nivel educativo.

Estudiantes que asisten a un nivel educativo y que tienen la edad teórica de asistencia a ese nivel, como porcentaje del total de la población en ese rango de edad. Las edades teóricas para cada país fueron calculadas en base a edades de ingreso y duración de cada nivel educativo, tal como establece la clasificación internacional normalizada de la educación de la UNESCO (ISCED 2011).

**Primaria:** El rango de edad estándar está entre 6 a 11 años. Hay algunas excepciones por países. El rango de edad en Colombia y Brasil está entre 6 a 10 años, en Barbados está entre 5 a 10 años, y en Trinidad y Tobago está entre 6 a 12 años.

**Secundaria:** El rango de edad estándar está entre 12 a 17 años. Hay algunas excepciones por países. El rango de edad en Costa Rica, Guatemala, Guyana, Jamaica, Nicaragua, Perú y Venezuela está entre 12 a 16 años. En Barbados está entre 11 a 15 años, en Colombia está entre 11 a 16 años, en Brasil está entre 11 a 17 años, en Haití y Suriname está entre 12 a 18 años, y en Trinidad y Tobago está entre 13 a 18 años.

**Superior:** El rango de edad estándar está entre 18 y 23 años. Hay algunas excepciones por países. El rango de edad en Costa Rica, Guatemala, Guyana, Jamaica, Nicaragua, Perú, Venezuela y Colombia está entre 17 a 23 años. En Haití, Suriname y Trinidad y Tobado está entre 19 a 23 años, y en Barbados está entre 16 a 23 años.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Indicadores de terminación {.unnumbered}

-   **Tasa de terminación escolar**

Se calcula como el número personas que han completado educación primaria o secundaria que tienen entre 3 y 5 años mayor a la edad teórica para el ingreso al último año de ese nivel (de acuerdo con el país) dividido entre la población total de ese grupo de edad.

**En educación primaria:** Porcentaje de niños y jóvenes con entre 3 y 5 años mayores a la edad teórica para finalizar primaria (de acuerdo con el país), que han completado ese nivel.

**En educación secundaria:** Porcentaje de jóvenes con entre 3 y 5 años mayores a la edad teórica para finalizar secundaria (de acuerdo con el país), que han completado ese nivel.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Indicadores de abandono {.unnumbered}

-   **Tasa de abandono escolar temprano**

Número de personas de entre 18 y 24 años que no finalizaron la educación secundaria y no asisten a ningún centro educativo entre el total de personas en ese rango de edad.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Indicadores de jóvenes que no trabajan ni estudian {.unnumbered}

-   **Porcentaje de jóvenes de entre 15 y 24 años que "Ni estudian Ni trabajan" (Ninis)** Número de personas de entre 15 y 24 años en condición de desempleo o inactividad (bajo la definición de la Organización Internacional del Trabajo) y no asisten a ningún centro educativo, sobre el total de personas en ese rango de edad.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Indicadores educativos de la población adulta {.unnumbered}

-   **Porcentaje de población adulta por años de educación**

De la población con 25 o más años, porcentaje de personas con: 0 años de educación finalizados, 1-5 años de educación finalizados, 6 años de educación finalizados, 7-11 años de educación finalizados, 12 años de educación finalizados o 13 años o más de educación finalizados. La suma de estas categorías es 100%.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

## Empleo y seguridad social

### Participación laboral {.unnumbered}

-   **Tasa global de participación**

Porcentaje de la población en edad de trabajar que participa activamente en el mercado de trabajo. Porcentaje que resulta de dividir el total de personas económicamente activas (PEA) entre el número de personas en edad de trabajar (PT). Se entiende como PEA es a aquella que se encuentran ocupada o desocupada. La PT se establece entre 16 y 64 años.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Tasa de ocupación**

Porcentaje que resulta del cociente entre el total personas ocupadas (O) y la población en edad de trabajar (PT). Se entiende como ocupado bajo esta definición a aquellas personas que han trabajado al menos una hora en el periodo de referencia (generalmente la última semana o el último mes si la encuesta pregunta por la semana), o que teniendo empleo no han trabajado por razones extraordinarias (licencia por enfermedad, huelga, vacaciones, etc.).

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Tasa de desocupación**

Porcentaje que resulta del cociente entre el total personas desocupadas y la población económicamente activa. Se entiende como desocupado (desempleado abierto) a aquellos que no trabajaron al menos una hora en el periodo de referencia, pero están disponibles para trabajar y han realizado gestiones concretas para encontrar trabajo. La población económicamente activa se refiere a la suma de la población ocupada y la desocupada.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Tasa de subocupación**

Porcentaje que resulta de dividir el número de trabajadores subocupados y el número total de la población ocupada. Se consideran como trabajadores subocupados a aquellos ocupados que trabajan 30 horas a la semana o menos, pero están dispuestas a trabajar más.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Empleo y seguridad social {.unnumbered}

-   **Formalidad**

Porcentaje que resulta del cociente entre el total personas ocupadas que cotizan a seguridad social en pensiones por su trabajo y el total de la población ocupada. Se utilizan afiliados en el caso que cotizantes no estén disponibles en la encuesta.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Tasa de autoempleo**

Porcentaje que resulta de dividir el número de trabajadores por cuenta propia y el número total de trabajadores ocupados. Los trabajadores por cuenta propia son aquellos que trabajan en su propia empresa o ejercen su profesión de forma independiente y no contratan empleados.

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

## Salud y protección social

### Financiamiento y recursos {.unnumbered}

-   **Camas hospitalarias por cada 10.000 habitantes**

Número de camas hospitalarias disponibles por cada 10.000 habitantes de una población.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/hospital-beds-(per-10-000-population))

-   **Médico por cada 10.000 habitantes**

Incluye a los generalistas, a los médicos especialistas y a los médicos no definidos con mayor detalle, en el ámbito nacional y/o subnacional de que se trate. Dependiendo de la naturaleza de la fuente de datos original, puede incluir solo médicos en ejercicio (activos) o todos los médicos registrados. Los códigos CIUO -08 incluidos aquí son 221,2211,2212.

El marco de la OMS para clasificar a los trabajadores de la salud se basa en las últimas revisiones de las clasificaciones internacionales, incluida la Clasificación Internacional Uniforme de Ocupaciones (revisión de 2008), la Clasificación Internacional Uniforme de la Educación (revisión de 2011) y la Clasificación Industrial Internacional Uniforme de Todas las Actividades Económicas (revisión 4).

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/medical-doctors-(per-10-000-population))

-   **Gastos en salud como porcentaje del PIB**

El gasto corriente en salud expresado como porcentaje del PIB incluye bienes y servicios de atención médica consumidos durante cada año. Este indicador no incluye gastos de capital en salud, como edificios, maquinaria, tecnología de la información y existencias de vacunas para emergencias o brotes. El gasto corriente en salud es igual a la suma del gasto público, privado y de bolsillo en salud.

**Fuente de datos:** [*Gasto en Salud Global de la Organización Mundial de la Salud -OMS.*](https://apps.who.int/nha/database/ViewData/Indicators/en)

### Determinantes sociales y estilo de vida {.unnumbered}

-   **Prevalencia de sobrepeso en adultos**

Porcentaje de personas de 18 años o más con un índice de masa corporal (IMC) de 25 kg/m² o más. Estandarizado por edad.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS.*](https://who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-overweight-among-adults-bmi-=-25-(age-standardized-estimate)-(-))

-   **Prevalencia de bajo peso al nacer**

El porcentaje de recién nacidos que pesan menos de 2 500 g (menos de 5,51 libras) al nacer.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/low-birth-weight-prevalence-(-))

-   **Porcentaje de población que utiliza al menos servicios básicos de saneamiento**

El porcentaje de personas que utilizan al menos servicios básicos de saneamiento corresponde al porcentaje de personas que utilizan instalaciones de saneamiento mejoradas que no se comparten con otros hogares. Las instalaciones de saneamiento mejoradas incluyen sistemas de alcantarillado con descarga, tanques sépticos o letrinas, letrinas mejoradas ventiladas, baños de compostaje o letrinas con losa.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/population-using-at-least-basic-sanitation-services-(-))

-   **Porcentaje de la población en pobreza que vive en un hogar beneficiario de PTMC**

Porcentaje de la población con ingresos entre \$3.1 y \$5.0 USD per cápita por día (2011 PPA) que vive en un hogar beneficiario de algún Programa de Transferencias Monetarias Condicionadas (PTMC).

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

-   **Porcentaje de beneficiarios en pobreza moderada**

Porcentaje de beneficiarios de Programa de Transferencias Monetarias Condicionadas (PTMC) con ingresos per cápita del hogar entre \$3.1 y \$5.0 USD (2011 PPA).

**Fuente de datos:** [*Encuestas Armonizadas de Hogares del BID*](#HHS)

### Servicios con calidad {.unnumbered}

-   **Cobertura de vacunación con BCG en niños de 1 año**

El porcentaje de nacidos vivos que han recibido una dosis de la vacuna Bacilo de Calmette-Guérin (BCG) en un año determinado.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/bcg-immunization-coverage-among-1-year-olds-(-))

-   **Índice de cobertura universal de servicios de salud**

Cobertura de los servicios esenciales de salud (definida como la cobertura media de los servicios esenciales basada en intervenciones de rastreo que incluyen la salud reproductiva, materna, neonatal e infantil, las enfermedades infecciosas, las enfermedades no transmisibles y la capacidad y el acceso a los servicios, entre la población general y la más desfavorecida). El indicador es un índice reportado en una escala sin unidades de 0 a 100, que se calcula como la media geométrica de 14 indicadores trazadores de la cobertura de los servicios de salud. Los indicadores trazadores son los siguientes, organizados por cuatro componentes de la cobertura de servicios: 1. Salud reproductiva, materna, neonatal e infantil 2. Enfermedades infecciosas 3. Enfermedades no transmisibles 4. Capacidad y acceso al servicio. Hace referencia al Objetivo de Desarrollo Sostenible 3.8.1.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/uhc-index-of-service-coverage)

### Vidas saludable {.unnumbered}

-   **Esperanza de vida al nacer**

El número promedio de años que un recién nacido podría esperar vivir, si pasara por la vida expuesto a las tasas de mortalidad específicas por sexo y edad que prevalecen en el momento de su nacimiento, durante un año específico, en un país, territorio o área geográfica determinados.

**Fuente de datos:** [*Instituto de Métricas y Evaluación de la Salud (IHME, por sus siglas en inglés)*](https://vizhub.healthdata.org/gbd-compare/#)

-   **Tasa de mortalidad para menores de 5 años por 1.000 nacidos vivos**

La tasa de mortalidad infantil es la probabilidad de que un niño nacido en un año o período específico muera antes de cumplir un año, si está sujeto a las tasas de mortalidad específicas por edad de ese período. En sentido estricto, la tasa de mortalidad infantil no es una tasa (es decir, el número de muertes dividido por el número de personas en riesgo durante un determinado período de tiempo), sino una probabilidad de muerte derivada de una tabla de vida y expresada como tasa por cada 1000 nacidos vivos.

**Fuente de datos:** [*Observatorio Mundial de la Salud - OMS*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/under-five-mortality-rate-(probability-of-dying-by-age-5-per-1000-live-births))

### Protección financiera {.unnumbered}

-   **Gasto de bolsillo como porcentaje del PIB**

El gasto de bolsillo como porcentaje del PIB estima cuánto gastan directamente los hogares en cada país en atención médica. Estima la proporción del gasto de bolsillo con respecto al gasto total actual en salud. El gasto de bolsillo en salud se define como cualquier gasto incurrido por un hogar cuando algún miembro utiliza un bien o servicio de salud para recibir cualquier tipo de atención (preventiva, curativa, de rehabilitación, de largo plazo o paliativa); proporcionado por cualquier tipo de proveedor; para cualquier tipo de enfermedad, afección o condición de salud; en cualquier tipo de entorno (ambulatorio, hospitalario, en el hogar).

**Fuente de datos:** [*Gasto en Salud Global de la Organización Mundial de la Salud - OMS.*](https://apps.who.int/nha/database/ViewData/Indicators/en)

-   **Población con gastos del hogar en salud superiores al 10% del gasto o ingreso total del hogar**

Porcentaje de la población con gastos del hogar en salud superiores al 10% del gasto o ingreso total del hogar. Es el indicador 3.8.2 de los Objetivos de Desarrollo Sostenible (ODS).

**Fuente de datos:** [*Gasto en Salud Global de la Organización Mundial de la Salud -OMS.*](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/population-with-household-expenditures-on-health-greater-than-10-of-total-household-expenditure-or-income-(sdg-3-8-2)-(-))
