# Data from a gender and diversity perspective {#gdi-eng}

In Latin America and the Caribbean (LAC), persistent gaps and challenges are faced by women and diverse population groups, including people who identify as part of indigenous, Afro-descendant, LGTBQ+, and people with disabilities. The need for quality data and indicators from a gender and diversity perspective is becoming increasingly apparent. This dashboard is expected to generate access to data and indicators disaggregated by gender and for diverse populations on demography, education, employment, and housing to support the research agenda and decision-making and public policy formulation. The data source is then detailed, a list of the available indicators is presented, and the subnational disaggregation methodology incorporated in the dashboard is described.

## Data source

One of the main challenges in measuring socioeconomic gaps affecting diverse population groups is that, since they represent a tiny proportion of the population in some contexts, the sample size of national surveys is insufficient to estimate disaggregated indicators. For this reason, this dashboard with a gender and diversity perspective described below is constructed using data from the latest [*Harmonized Population and Housing Censuses*](#HC-eng) available for each country.

## Indicators

### Demography {.unnumbered}

-   **Population by Age Range**

It is calculated as the percentage of the population at a specific age out of the total population. In this context, the sum of the percentages of all age groups represented in the population pyramid should equal 100 percent.

The age ranges defined to calculate these indicators are as follows: 0 to 15 years, 16 to 30 years, 31 to 45 years, 46 to 60 years, 61 to 75 years, and 76 years or more.

-   **Diversity Groups**

-   *Indigenous population*

It is calculated as the number of people who self-identify as Indigenous according to the national ranking of the total population.

*Learn more about how diversity information is obtained:* [*see Recommendation on Diversity Data in the Social*](https://publications.iadb.org/en/recommendations-diversity-data-social-sector)

-   *Afro-descendant population*

It is calculated as the number of people who self-identify as Afro-descendant according to the national classification of the total population.

*Learn more about how diversity information is obtained:* [*see Recommendation on Diversity Data in the Social*](https://publications.iadb.org/en/recommendations-diversity-data-social-sector)

-   *Population with disabilities*

It is calculated as the number of people who report having at least some difficulty with activities based on the domains of the [*Washington Group's*](https://www.washingtongroup-disability.com/fileadmin/uploads/wg/Documents/Questions/Washington_Group_Questionnaire__1_-_WG_Short_Set_on_Functioning__June_2022_.pdf) questions on the total population.

The questions of the Washington Group are one of the most widely accepted methods of measuring disability in national surveys, as they focus on people who have difficulty performing daily activities, such as walking, seeing, or remembering. The conceptualization of the questions used to identify the population with disabilities is based on the model of the [*World Health Organization's International Classification of Functioninf, Disability and Health (ICF)*](https://www.who.int/classifications/international-classification-of-functioning-disability-and-health).

### Employment {.unnumbered}

-   *Labor Force Participation*

Percentage of the working-age population actively participating in the labor market. It is the result of dividing the total number of economically active population (EAP) by the number of working-age people. EAP is understood to be the population that is employed or unemployed. The working age population is between 16 and 64 years old.

-   *Unemployment rate*

The ratio of the total number of unemployed persons to the economically active population. Unemployed (openly unemployed) are understood to be those who did not work at least one hour in the reference period but are available for work and have made concrete arrangements to find a job. The economically active population is the sum of the employed and unemployed population.

### Education {.unnumbered}

-   *School Completion Rate*

The percentage of people who have completed primary or secondary education and are 3 to 5 years older than the theoretical age for entry into the final year of that level (depending on the country) divided by the total population of that age group.

*In primary education:* Percentage of children and young people 3 to 5 years older than the theoretical age to finish primary school (according to the country) who have completed that level.

*In secondary education:* Percentage of young people 3 to 5 years older than the theoretical age to finish secondary school (according to the country) who have completed that level.

### Housing {.unnumbered}

*Electricity:* Access is identified when households report that the primary lighting source is public or private.

*Aqueduct water:* Access is defined as households reporting that the primary water source for consumption is the public distribution network.

*Internet:* The household reports having access to a local internet connection.

*Car:* The household reports that at least one of its members owns a car.

*Cell Phone:* Access is defined as at least one person in the household having cell phone service.

## Subnational disaggregation

The subnational disaggregation used in this dashboard is based on the administrative units of the Harmonized Population and Housing Censuses of [@IPUMS][^03-gyd-1]. Specifically, the 6-digit numerical variable Geolev1 is used to perform the geographic grouping. This variable indicates the administrative unit (state, department, province, among others) in which the household was registered. Since the microdata series of the censuses are harmonized with respect to previous censuses and some of the administrative units have changed, an exercise of harmonization of the administrative units is carried out to make them comparable between censuses. In most cases, this implies that some administrative units, according to the IPUMS code, group more than one organizational unit according to the current political division of countries. For example, in Colombia, Bogotá D.C. and Cundinamarca are currently distinct administrative units; however, these are grouped in IPUMS with the code 170011.

[^03-gyd-1]: Available: https://international.ipums.org/international/resources/misc_docs/geolevel1.pdf (January 2022).

It is essential to mention that administrative units are combined to create a single unit in the following cases: (i) large units are divided in later years, (ii) whole units or parts of units are combined in new ways, or (iii) the boundaries between units change from census to census. Combined units generally retain the code of the unit with the highest population in the most recent IPUMS international census sample.
