# Fonte de dados {#source-pt}

Esta seção descreve as fontes de dados usadas para calcular os indicadores disponíveis na plataforma [**Dados e indicadores para a América Latina e o Caribe**](https://www.iadb.org/en/sharing-knowledge/data/social-data) e nos pacotes IDBsocialdata que estão disponíveis para uso em linguagem  [**R**](https://github.com/EL-BID/idbsocialdataR), [**Python**](https://github.com/EL-BID/idbsocialdatapy) e [**Stata**](https://github.com/EL-BID/idbsocialdata).

## Pesquisas domiciliares harmonizadas do BID {#HHS-pt}

As Pesquisas Domiciliares (PD) são usadas como fonte de referência para observar e analisar as características demográficas, econômicas e sociais dos países. No intuito de fornecer dados comparáveis ao longo do tempo e entre diferentes nações, a padronização dos bancos de dados originais é realizada seguindo uma abordagem e uma estrutura comuns, incluindo nomes, definições e desagregações uniformes. Esse processo de harmonização permite que os usuários economizem tempo no processamento de dados e gerem informações analíticas em nível regional e sub-regional usando critérios uniformes. Além disso, facilita a realização de diagnósticos, a formulação de estratégias e a pesquisa sobre questões sociais específicas em cada país da região.

Para realizar a padronização das variáveis de acordo com as diretrizes estabelecidas, é disponibilizado o [**repositório de harmonização de pesquisas **](https://github.com/EL-BID/armonizacion_microdatos_encuestas_hogares_scl) que contém os scripts do Stata e a documentação necessária para gerar os dados.

É importante observar que a principal fonte dos microdados originais das PDs são os institutos de estatística (INEs) dos países da região. Em casos específicos, o BID participa como coprodutor de algumas dessas pesquisas. A seguir são listadas as fontes e as pesquisas disponíveis:

| **País**  | **Fonte**                                                    | **Pesquisa**                                                    | **Anos disponíveis**                  |
|-----------|---------------------------------------------------------------|-----------------------------------------------------------------|---------------------------------------|
| **ARG**   | Instituto Nacional de Estadísticas y Censos (INDEC)           | Encuesta Permanente de Hogares - Continua (EPHC)                | 2003-2022                             |
|           |                                                               | Encuesta Permanente de Hogares - Puntual (EPHP)                 | 1992-2002                             |
| **BHS**   | Bahamas National Satatistical Institute                       | Labor Force Survey (LFS)                                        | 2001-2009, 2011-2024                  |
| **BLZ**   | Statistical Institute of Belize                               | Labor Force Survey (LFS)                                        | 1993-1999, 2001-2005, 2007            |
| **BOL**   | Instituto Nacional de Estadística (INE)                       | Encuesta Continua de Hogares (ECH)                              | 1999-2021                             |
|           |                                                               | Encuesta Nacional de Empleo (ENE)                               | 1996-1997                             |
|           |                                                               | Encuesta Integrada de Hogares (EIH)                             | 1990-1995                             |
| **BRA**   | Instituto Brasileiro de Geografía e Estadística (IBGE)        | Pesquisa Nacional por Amostra de Domicilio Continua (PNAD)      | 2016-2022                             |
|           |                                                               | Pesquisa Nacional por Amostra de Domicilio (PNAD)               | 1990-2015                             |
| **BRB**   | Barbados Statistical Service                                  | Continuous Labor Force Survey (CLFS)                            | 1999, 2004-2016                       |
| **CHL\*** | Ministerio de Desarrollo Social (MIDEPLAN)                    | Encuesta de Caracterización Socioeconómica Nacional (CASEN)     | 1990-2022                             |
| **COL**   | Departamento Administrativo Nacional de Estadística (DANE)    | Gran Encuesta Integrada de Hogares (GEIH)                       | 2006-2022                             |
|           |                                                               | Encuesta Continua de Hogares (ECH)                              | 2001-2005                             |
|           |                                                               | Encuesta Nacional de Hogares - Fuerza de Trabajo (ENH-FT)       | 1990-2000                             |
| **CRI**   | Instituto Nacional de Estadísticas y Censos (INEC)            | Encuesta Nacional de Hogares (ENAHO)                            | 2010-2022                             |
|           |                                                               | Encuesta de Hogares de Propósitos Múltiples (EHPM)              | 1990-2009                             |
| **DOM**   | Banco Central de la República Dominicana (BCRD)               | Encuesta Nacional de Fuerza de Trabajo Continua (ENCFT)         | 2017-2021                             |
|           |                                                               | Encuesta Nacional de Fuerza de Trabajo (ENFT)                   | 1994-1996, 2000-2016                  |
| **ECU**   | Instituto Nacional de Estadística y Censos (INEC)             | Encuesta Nacional de empleo, desempleo y subempleo (ENEMDU)     | 1990-2022                             |
| **GTM**   | Instituto Nacional de Estadística (INE)                       | Encuesta Nacional de Empleo e Ingresos (ENEI)                   | 2002-2004, 2010-2022                  |
|           |                                                               | Encuesta Nacional de Condiciones de Vida (ENCOVI)               | 2000, 2006, 2011, 2014                |
|           |                                                               | Encuesta Nacional de Ingresos y Gastos Familiares (ENIGF)       | 1998                                  |
| **GUY**   | Bureau of Statistics                                          | Labor Force Survey (LFS)                                        | 2016-2018, 2021                       |
| **HND**   | Instituto Nacional de Estadísticas (INE)                      | Encuesta Permanente de Hogares de Propósitos Múltiples (EPHPM)  | 1990-1999, 2000-2019                  |
| **HTI**   | Institut Haiten De Statistique et D'Informatique - World Bank | Enquete Les Conditions de Vie des Menages Apres Seisme (ECVMAS) | 2012                                  |
| **JAM**   | Statistical Institute of Jamaica (STATIN)                     | Labour Force Survey (LFS)                                       | 1990-2010, 2012-2014, 2016, 2019-2020 |
| **MEX\*** | Instituto Nacional de Estadística y Geografía (INEGI)         | Encuesta Nacional de Ingresos y Gastos de los Hogares (ENIGH)   | 1992-2022                             |
| **NIC**   | Instituto Nacional de Información de Desarrollo (INIDE)       | Encuesta Continua de Hogares (ECH)                              | 2010-2012                             |
|           |                                                               | Encuesta de Hogares sobre medición de Niveles de Vida (EMNV)    | 1993, 1998, 2001, 2005, 2009, 2014    |
| **PAN**   | Instituto Nacional de Estadística y Censo (INEC)              | Encuesta de Hogares de Propósitos Múltiples (EHPM)              | 2011-2019, 2022                       |
|           |                                                               | Encuesta de Hogares (EH)                                        | 1991-2009                             |
| **PRY**   | Dirección General de Estadística, Encuestas y Censos (DGEEC)  | Encuesta Permanente de Hogares Continua (EPHC)                  | 2018                                  |
|           |                                                               | Encuesta Permanente de Hogares (EPH)                            | 1999, 2002-2017                       |
|           |                                                               | Encuesta Integrada de Hogares (EIH)                             | 1997-98, 2000-01                      |
|           |                                                               | Encuesta de Hogares - Mano de Obra (EHM)                        | 1990-1996                             |
| **PER**   | Instituto Nacional de Estadística e Informática (INEI)        | Encuesta Nacional de Hogares (ENAHO)                            | 1997-2022                             |
| **SLV**   | Dirección General de Estadística y Censos (DIGESTYC)          | Encuesta de Hogares de Propósitos Múltiples (EHPM)              | 1995-2022                             |
| **SUR**   | Banco Interamericano de Desarrollo (BID)                      | Suriname Survey of Living Conditions (SSLC)                     | 2017, 2022                            |
| **TTO**   | Central of Trinidad and Tobago                                | Continuous Sample Survey of Population (CSSP)                   | 1999-2014                             |
| **URY**   | Instituto Nacional de Estadística (INE)                       | Encuesta Continua de Hogares (ECH)                              | 1992, 1995-2022                       |
| **VEN**   | Instituto Nacional de Estadística (INE)                       | Encuesta de Hogares por Muestreo (EHM)                          | 1991-2013                             |
|           | UCAB-USB-UCENTRAL, BID, World Bank                            | Encuesta Nacional de Condiciones de Vida (ENCOVI)               | 2014-2019, 2021                       |

\*As pesquisas no México e no Chile são realizadas a cada dois e três anos, respectivamente.

## Censos de População e Habitação Harmonizados do BID {#HC-pt}

Os Censos de População e Habitação têm como objetivo fornecer informações sobre o número, a estrutura e a distribuição geográfica da população em cada país. Assim como na coleção PD, o objetivo é gerar dados padronizados e comparáveis entre países e ao longo do tempo a partir das informações compartilhadas pelo Integrated Public Use Microdata (IPUMS) da Universidade de Minnesota. Nos casos em que os censos não estão disponíveis no IPUMS, os INEs de cada país são usados como fonte de dados.

Com base nas informações obtidas no  [@IPUMS], é realizada uma padronização seguindo as diretrizes estabelecidas pelo BID. Os Scripts em Stata e os documentos de harmonização de variáveis estão disponíveis no [*repositório de harmonização do censo*](). A seguir são descritas as fonte e os dados disponíveis:

| **País** | **Fonte**                                                   | **Anos disponíveis**                 |
|----------|--------------------------------------------------------------|------------------------------------|
| **ARG**  | IPUMS, Minnesota Population Center                           | 1970, 1980, 1991, 2001, 2010       |
| **BHS**  |                                                              | No disponible                      |
| **BLZ**  |                                                              | No disponible                      |
| **BOL**  | IPUMS, Minnesota Population Center                           | 1976,1992, 2001, 2012              |
| **BRA**  | IPUMS, Minnesota Population Center                           | 1960, 1970, 1980, 1991, 2000, 2010 |
| **CHL**  | IPUMS, Minnesota Population Center                           | 1970, 1982, 1992, 2017             |
| **COL**  | IPUMS, Minnesota Population Center                           | 1963,1973, 1985, 1993, 2005        |
|          | Departamento Administrativo Nacional de Estadística (DANE)   | 2018                               |
| **CRI**  | IPUMS, Minnesota Population Center                           | 1963, 1973, 1984, 2000, 2010       |
| **DOM**  | IPUMS, Minnesota Population Center                           | 1960,1970, 1980, 2002, 2010        |
| **ECU**  | IPUMS, Minnesota Population Center                           | 1962,1974, 1981, 1989, 2001, 2010  |
| **GTM**  | IPUMS, Minnesota Population Center                           | 1963, 1973, 1980, 1993, 2002       |
|          | Instituto Nacional de Estadística (INE)                      | 2018                               |
| **GUY**  | Department of Public Information (DPI)                       | 1991, 2001, 2012                   |
| **HND**  | IPUMS, Minnesota Population Center                           | 1961,1973, 1988, 2001              |
| **HTI**  | IPUMS, Minnesota Population Center                           | 1970,1982, 2003                    |
| **JAM**  | IPUMS, Minnesota Population Center                           | 1982,1991, 2001                    |
|          | Statistical Institute of Jamaica (STATIN)                    | 2011                               |
| **MEX**  | IPUMS, Minnesota Population Center                           | 1960,1970, 1995, 2005, 2015        |
|          | Instituto Nacional de Estadística y Geografía (INEGI)        | 1989, 2000, 2010, 2020             |
| **NIC**  | IPUMS, Minnesota Population Center                           | 1971,1995, 2005                    |
| **PAN**  | IPUMS, Minnesota Population Center                           | 1960,1970, 1980, 1990, 2000, 2010  |
| **PER**  | IPUMS, Minnesota Population Center                           | 1993, 2007                         |
|          | Instituto Nacional de Estadística e Informática (INEI)       | 2017                               |
| **PRY**  | IPUMS, Minnesota Population Center                           | 1962,1972, 1982, 1992, 2002        |
|          | Dirección General de Estadística, Encuestas y Censos (DGEEC) | 2012                               |
| **SLV**  | IPUMS, Minnesota Population Center                           | 1992, 2007                         |
| **SUR**  | IPUMS, Minnesota Population Center                           | 2004, 2012                         |
| **TTO**  | IPUMS, Minnesota Population Center                           | 1970,1980, 1990, 2000, 2011        |
| **URY**  | IPUMS, Minnesota Population Center                           | 1963, 1975, 1985, 1996, 2006, 2011 |
| **VEN**  | IPUMS, Minnesota Population Center                           | 1971, 1981, 1990, 2001             |

